# Generated by Django 2.2.3 on 2020-01-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurements', '0002_baseuser_production_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='inn',
            field=models.BigIntegerField(null=True, verbose_name='ИНН заказчика'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='kpp',
            field=models.BigIntegerField(null=True, verbose_name='КПП заказчика'),
        ),
    ]
