# Generated by Django 2.2.3 on 2020-01-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurements', '0003_auto_20200125_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='email',
            field=models.CharField(max_length=64, null=True, verbose_name='E-Mail'),
        ),
    ]
