# Generated by Django 2.2.3 on 2020-01-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurements', '0007_auto_20200125_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='phone',
            field=models.CharField(max_length=64, null=True, verbose_name='Телефон контактного лица'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='phone',
            field=models.CharField(max_length=64, null=True, verbose_name='Телефон организации'),
        ),
    ]
