# Generated by Django 2.2.3 on 2020-01-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurements', '0008_auto_20200125_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='last_seen',
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='inn',
            field=models.CharField(max_length=64, null=True, verbose_name='ИНН заказчика'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='kpp',
            field=models.CharField(max_length=64, null=True, verbose_name='КПП заказчика'),
        ),
        migrations.AlterUniqueTogether(
            name='baseuser',
            unique_together=set(),
        ),
    ]
