# Generated by Django 2.2.3 on 2020-01-25 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurements', '0009_auto_20200125_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='registration_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='procurements.Region', verbose_name='Регион регистрации'),
        ),
    ]
