# Generated by Django 2.2.3 on 2020-01-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurements', '0010_auto_20200125_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование поставщика'),
        ),
    ]
