# Generated by Django 2.2.3 on 2020-01-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurements', '0011_auto_20200125_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='characteristic',
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic',
            field=models.ManyToManyField(blank=True, to='procurements.Characteristic', verbose_name='Характеристики'),
        ),
    ]
