# Generated by Django 2.2.3 on 2020-01-25 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurements', '0012_auto_20200125_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='characteristic',
            new_name='characteristics',
        ),
    ]
