# Generated by Django 2.2.3 on 2020-01-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurements', '0013_auto_20200125_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='num_of_contracts',
            field=models.IntegerField(null=True, verbose_name='Количество контрактов'),
        ),
        migrations.AlterField(
            model_name='product',
            name='num_of_offers',
            field=models.IntegerField(null=True, verbose_name='Количество действующих оферт'),
        ),
    ]
