# Generated by Django 2.2.3 on 2020-01-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurements', '0014_auto_20200125_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='price',
            field=models.FloatField(verbose_name='Цена одной единицы товара'),
        ),
    ]
