# Generated by Django 2.2.3 on 2020-01-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurements', '0016_auto_20200125_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='num_of_contracts',
            field=models.IntegerField(null=True, verbose_name='Количество контрактов на ПП'),
        ),
    ]
