# Generated by Django 2.2.3 on 2020-01-25 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurements', '0017_auto_20200125_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='production_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='procurements.ProductionType', verbose_name='Вид продукции'),
        ),
    ]
