# Generated by Django 2.2.3 on 2020-01-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurements', '0020_auto_20200125_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='title',
            field=models.TextField(null=True, verbose_name='Предмет закупки'),
        ),
    ]
